config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'static_pages#index'
  get '/signup', to: 'users#new'
  get'/login',to: 'sessions#new'
  post'/login',to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  scope "(:locale)", locale: /en|vi/ do
    resources :users
    resources :tours
    resources :requests, only: [:show, :new, :create]

    namespace :admin do
      get '/index', to: 'static_pages#index'
      get 'static_pages/help'
      resources :requests, only: [:show, :index, :delete, :update]
      resources :tours, except:[:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking_tour.rb
class BookingTuor < ApplicationRecord
	belongs_to :user
	belongs_to :tour
end

app/models/booking_tuor.rb
class BookingTuor < ApplicationRecord
	belong_to :user
	belong_to :tour
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :review
	has_many :like
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  belongs_to :review
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  belongs_to :comment
end

app/models/oauth.rb
class Oauth < ApplicationRecord
  belongs_to :user
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
	belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
	belong_to :user
	has_many :comments
	has_many :likes
end

app/controllers/admin/requests_booking_controller.rb
class Admin::RequestsBookingController < ApplicationController
  def index
  end

end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :find_tour, except: :index

  def index
    @tours = Tour.paginate(page: params[:page])
  end

  def edit
  end

  def show
  end
  def update
    host_user = params[:host_user] + "!"
    @tour.send(host_user)
    respond_to do |format|
      format.html { redirect_to admin_tours_path }
      format.js
    end
  end

  def destroy
    @tour.destroy
    redirect_to admin_tours_path
  end
  private
  def find_tour
    @tour =  Tour.find_by id: params[:id]
    unless @tour.present?
      flash[:danger] = "Can not find tour"
      redirect_to admin_tours_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
     before_action :logged_in_user, only: [:create, :edit]

      def new
        @request = Request.new
        stayed_days = Date.parse(params[:day_end]).mjd - Date.parse(params[:day_start]).mjd
        if ( stayed_days <= 0 )
          render :new
        else
          total_price = stayed_days * params[:tour_price].to_f
          render json: total_price
        end
      end

      def show
        @request = Request.find(param[:id])
      end

      def create
        @request = current_user.requests.new request_params
        if @request.save!
          flash[:success] = "Booking success"
          redirect_to tour_path(request_params[:tour_id])
        else
          flash[:danger] = "Save loi"
          render :new
        end
      end

      def update
        if @request.update(request_params)
        else
          render :edit
        end
      end

      private
      def request_params
        params.require(:request).permit(:tour_id, :price, :day_start, :day_end, :gues)
      end

      def find_request
        @request = Request.find_by id: params[:request_id]
        unless @request.present?
    			flash[:success] = "Request doesn't exist"
    			redirect_to root_url
    		end
    	end
      
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
	before_action :find_tour, only: [:show]
	before_action :logged_in_user, only: [:new, :create, :destroy, :edit, :update,]
	before_action :correct_user, only: [ :edit, :destroy]

	def new
		@tour=Tour.new
	end

	def edit
	end

	def index
		@tours = Tour.paginate(page: params[:page]).per_page(20)
	end

	def show

		arr_rates = @tour.rates
		sum = 0
		arr_rates.each do|rate|
			sum+=rate.quantity
		end
		if sum > 0
			@total = sum/arr_rates.length
		end
	end

	def update
		if @tour.update(tour_params)
			redirect_to @tour
		else
			render 'edit'
		end
	end

	def create
		@tour = current_user.tours.build(tour_params)
		@tour.image.attach(params[:tour][:image])
		if @tour.save
			redirect_to @tour
			flash[:success] = I18n.t ('controllers.admin.create')
		else
			render :new
		end
	end

	private

	def find_tour
		@tour = Tour.find_by id: params[:id]
		@request = Request.new
		unless @tour.present?
			flash[:success] = "Tour doesn't exist"
			redirect_to root_url
		end
	end

	def tour_params
		params.require(:tour).permit(:title, :guest, :address, :phone_number, :price, :rules,:content,
		:description, :host, :status,:room,:bed, :bathroom, :house_type, :image,  convenient:[],
		furniture:[],)
	end
	def correct_user
		@tour = current_user.tours.find_by(id: params[:id])
		redirect_to root_url if @tour.nil?
	end

end

app/helpers/admin/requests_booking_helper.rb
module Admin::RequestsBookingHelper
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/destroy_helper.rb
module DestroyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget current_user
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
  def checked(area)
    @tour.convenient.nil? ? false : @tour.convenient.match(area)
  end
  def checked2(area)
    @tour.furniture.nil? ? false : @tour.furniture.match(area)
  end
end

app/views/admin/tours/_host.html.erb
<%= link_to 'Back', admin_tours_path, class:'btn btn-secondary mt-3'%>
<% if @tour.host_user == 'draft'%>
<%= link_to 'Publish', admin_tour_path(@tour, host_user: 'publish'), method: :patch ,data: { confirm: "You sure?" }, remote: true, class: 'btn btn-info mt-3'%>
<% else%>
<%= link_to 'Unpublish', admin_tour_path(@tour, host_user: 'draft'), method: :patch ,data: { confirm: "You sure?" }, remote: true, class: 'btn btn-info mt-3'%>
<% end %>
<%= link_to 'Destroy', admin_tour_path(@tour), method: :delete, data: { confirm: 'Are you sure?'},class:'btn btn-danger mt-3'%>

app/views/admin/tours/index.html.erb
<h4 class="d-flex justify-content-between mb-4">
  <span>New Tour</span>
</h4>
<% @tours.each do |tour|%>
<%= link_to admin_tour_url(tour) ,class:'text-decoration-none' do%>
<div class="card mb-3">
  <div class="card-body">
    <div class="row">
      <div class="col-md-2">
        <%= image_tag tour.image, width: "120", height: "100" if tour.image.attached? %>
      </div>
      <div class="col-md-10">
        <div class="tack">
          <h5 clase="card-title mb-1 text-dark"><%=tour.title%></<h5>
            <% if tour.host_user == 'publish' %>
            <h5 class="badge badge-primary"><%= t('.publish') %> </h5>
            <% else %>
            <h5 class="badge badge-danger"><%= t('.draft') %> </h5>
            <% end %>
          </div>
          <p class="text-secondary mb-0"><%= tour.description%></p>
        </div>
      </div>
    </div>
  </div>
  <%end%>
  <%end%>

app/views/admin/tours/show.html.erb
<div id="host">
  <%= render 'host'%>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="fr4mbd">
          <div class="index-tours-sheet">
            <section class="secs">
              <span class="font-title"><%= @tour.title %></span>
              <div class="adr">
                <div class="star"><img src="../../assets/star.svg" width="15px"height="15px"></div>
                <% if @tour.rates.any? %>
                  <div class="font-content-r"><%= @total %></div>
                  <div class="font-content-s">(<%= @tour.rates.count %>)</div>
                  <div class="font-content-d"><%= @tour.address %></div>
                <%else%>
                  <div class="font-content-r">(New)</div>
                  <div class="font-content-d"><%= @tour.address %></div>
                <%end%>
              </div>
            </section>
            <section class="secs">
              <div class="container-f">
                <div class="z1">
                  <div class="z1i">
                    <%= image_tag @tour.image if @tour.image.attached? %>
              </div>
            </section>
            <section class="secs">
              <div class="container-s3">
                <div class="pA">
                  <div class="pA1">
                    <div class="pA80">
                      <div class="pA801"><%= @tour.house_type%><span>. Chủ nhà: <%=@tour.user.name%></span></div>
                      <div class="pA802"><%= @tour.guest%> khách - <%= @tour.room%> phòng - <%= @tour.bed%> giường - <%= @tour.bathroom%> phòng tắm </div>
                    </div>
                    <div class="pA20">
                      <div class="ava"><%= link_to gravatar_for(current_user, size:56)%></div>
                    </div>
                  </div>
                  <div class="pAi">
                    <%= @tour.description%>
                  </div>
                  <div class="pAi">
                    <h3 tabindex="-1">Không gian có thể sử dụng</h3>
                    <%= @tour.furniture%>
                  </div>
                  <div class="pAi">
                    <h3 tabindex="-1" >Tiện nghi</h3>
                    <%= @tour.convenient%>
                  </div>
                  <div class="pAi">
                    <h3 tabindex="-1" >Những điều cần biết</h3>
                    <span><%= @tour.rules%></span>
                    <span>Thời gian nhận phòng </span><%= @tour.content%>
                  </div>
                </div>
                <div class="pAi">
                </div>
              </div>
            </section>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/tours/update.js.erb
$("#host").html("<%= escape_javascript(render 'admin/tours/host') %>")

app/views/tours/_tour.html.erb
<% if tour.host_user == 'publish' %>
<div class="content-tour-i">
  <div class="mar-container">
    <%= link_to tour do %>
      <div class="frame-image">
        <%= image_tag tour.image ,class:"image" if tour.image.attached? %>
      </div>
      <div class="star"><img src="../assets/star.svg" width="15px"height="15px"> 4.50 <span>(12)</span></div>
      <div class="infor"><%= tour.title %><%= tour.address %></div>
      <div class="infor"><span><%= tour.description %></span></div>
      <div class="infor"><span class="text">$<span><%= tour.price %>/đêm</span></span></div>
    <% end %>
  </div>
</div>
<%end%>

app/views/tours/edit.html.erb
<%= javascript_pack_tag 'tour', 'data-turbolinks-track': 'reload' %>
<% provide(:title, "Become a host") %>
<div class="bchost">
  <div class="host">
    <div class="hostpa">
      <%= render 'form_for'%>
    </div>
    <div class="hostpb">
      <div class="_d6tm0n">
        <div class="_1ouw2w0">
          <svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" style="display:block;height:32px;width:32px;fill:currentColor" aria-hidden="true" role="presentation" focusable="false">
            <path d="M24.6666 11.1332V11.5332C24.5999 14.3332 22.9333 17.0665 19.5333 19.7998L19.3333 19.9998H12.6666L12.3999 19.7998C8.99994 17.0665 7.33327 14.3332 7.2666 11.5332V11.1332C7.4666 6.4665 11.2666 2.6665 15.9999 2.6665C20.7333 2.6665 24.5999 6.4665 24.6666 11.1332Z" fill="#64DEE2"></path><path d="M27.3334 11.3333C27.3334 5.06667 22.2667 0 16.0001 0C9.73342 0 4.66675 5.06667 4.66675 11.3333C4.66675 15.2667 6.93341 18.9333 11.3334 22.3333V29.3333C11.3334 30.0667 11.9334 30.6667 12.6667 30.6667H15.3334V32H16.6667V30.6667H19.3334C20.0667 30.6667 20.6667 30.0667 20.6667 29.3333V22.3333C25.0667 18.9333 27.3334 15.2667 27.3334 11.3333ZM19.3334 29.3333H12.6667V26.6667H19.3334V29.3333ZM19.3334 25.3333H12.6667V22.6667H19.3334V25.3333ZM17.3334 21.3333H14.6667V11.3333C14.6667 10.6 15.2667 10 16.0001 10C16.7334 10 17.3334 10.6 17.3334 11.3333V21.3333ZM19.8001 21.3333H18.6667V11.3333C18.6667 9.86667 17.4667 8.66667 16.0001 8.66667C14.5334 8.66667 13.3334 9.86667 13.3334 11.3333V21.3333H12.2001C8.06675 18.2 6.00008 14.8 6.00008 11.3333C6.00008 5.8 10.4667 1.33333 16.0001 1.33333C21.5334 1.33333 26.0001 5.8 26.0001 11.3333C26.0001 14.8 23.9334 18.2 19.8001 21.3333Z" fill="#222222">
            </path>
          </svg>
        </div>
        <div class="help-panel__text">
          <div class="_1p7iugi">Chọn các danh mục của nhà/phòng cho thuê</div>
          <div class="_1js7ixe">Việc chọn các danh mục chính xác giúp khách biết họ có thể mong đợi những gì khi nói đến sự riêng tư, phong cách và cấp độ dịch vụ mà họ sẽ nhận được trong thời gian ở chỗ của bạn.</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tours/new.html.erb
<%= javascript_pack_tag 'tour', 'data-turbolinks-track': 'reload' %>
<% provide(:title, t('.become')) %>
<div class="bchost">
  <div class="host">
    <div class="hostpa">
      <%= render 'form_for'%>
    </div>
    <div class="hostpb">
      <div class="_d6tm0n">
        <div class="_1ouw2w0">
          <svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" style="display:block;height:32px;width:32px;fill:currentColor" aria-hidden="true" role="presentation" focusable="false">
            <path d="M24.6666 11.1332V11.5332C24.5999 14.3332 22.9333 17.0665 19.5333 19.7998L19.3333 19.9998H12.6666L12.3999 19.7998C8.99994 17.0665 7.33327 14.3332 7.2666 11.5332V11.1332C7.4666 6.4665 11.2666 2.6665 15.9999 2.6665C20.7333 2.6665 24.5999 6.4665 24.6666 11.1332Z" fill="#64DEE2"></path><path d="M27.3334 11.3333C27.3334 5.06667 22.2667 0 16.0001 0C9.73342 0 4.66675 5.06667 4.66675 11.3333C4.66675 15.2667 6.93341 18.9333 11.3334 22.3333V29.3333C11.3334 30.0667 11.9334 30.6667 12.6667 30.6667H15.3334V32H16.6667V30.6667H19.3334C20.0667 30.6667 20.6667 30.0667 20.6667 29.3333V22.3333C25.0667 18.9333 27.3334 15.2667 27.3334 11.3333ZM19.3334 29.3333H12.6667V26.6667H19.3334V29.3333ZM19.3334 25.3333H12.6667V22.6667H19.3334V25.3333ZM17.3334 21.3333H14.6667V11.3333C14.6667 10.6 15.2667 10 16.0001 10C16.7334 10 17.3334 10.6 17.3334 11.3333V21.3333ZM19.8001 21.3333H18.6667V11.3333C18.6667 9.86667 17.4667 8.66667 16.0001 8.66667C14.5334 8.66667 13.3334 9.86667 13.3334 11.3333V21.3333H12.2001C8.06675 18.2 6.00008 14.8 6.00008 11.3333C6.00008 5.8 10.4667 1.33333 16.0001 1.33333C21.5334 1.33333 26.0001 5.8 26.0001 11.3333C26.0001 14.8 23.9334 18.2 19.8001 21.3333Z" fill="#222222">
            </path>
          </svg>
        </div>
        <div class="help-panel__text">
          <div class="_1p7iugi"><%= t('.choose')%></div>
          <div class="_1js7ixe"><%= t('.tagg')%></div>
        </div>
      </div>
    </div>
  </div>
</div>